name: Tracer cron pipeline

on:
  schedule:
    - cron: '0 0,8,16 * * *'  # every 8 hours (00h00, 08h00, 16h00 UTC)
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y jq bc curl

      - name: Run tests script
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/test_results.csv
