name: Tracer cron pipeline

permissions:
  contents: write

on:
  #schedule:
  #  - cron: '0 0,8,16 * * *'  # every 8 hours (00h00, 08h00, 16h00 UTC)
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y jq bc curl

      - name: Run tests script
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh

      - name: Upload test results to a dedicated artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/test_results.csv
          include-hidden-files: true

      - name: Append results to a global repo file
        run: |
          cat results/test_results.csv >> cumulative_results.csv
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cumulative_results.csv
          git commit -m "Append test results [skip ci]"
          git push